version: '3.8'
volumes: 
  pg-vol:

networks:
  db-acess:
    driver: bridge
    name: db-acess

services:  
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - pg-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db-acess 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    restart: always
  spring-api:  
    image: brenolima69/spring-api:latest
    container_name: spring-api
    build: .
    ports:
      - 8084:8084
    networks:
      - db-acess
    depends_on:
      - postgres
    restart: always