version: '3.8'
volumes: 
  pg-vol:

networks:
  db-acess:
    driver: bridge
    name: db-acess

services:
  api:  
    image: brenolima69/spring-api:latest
    container_name: spring-api
    ports:
      - 8084:8084
    depends_on:
      - postgres
    networks:
      - db-acess
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - pg-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - db-acess
    environment:
      POSTGRES_DB: spring_boot
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--schema=spring_data"
